# Splunk Universal Forwarder — outputs.conf (production)
# Forwards all krittika:* data to Splunk Cloud via HEC and TCP

[tcpout]
defaultGroup = default-autolb-group

[tcpout:default-autolb-group]
server = prd-p-vce8j.splunkcloud.com:9997

[tcpout-server://prd-p-vce8j.splunkcloud.com:9997]
